export const API_BE = "http://localhost:5001/api";
export const BLOCK_ORG = [
    'Ipko',
    'Kosoves',
    'Artmotion',
    'Amazon',
    'Kujtesa',
    'Telkos',
    'META',
    'SlashNext',
    'Microsoft',
    'META PLATFORMS',
    'IP Volume inc',
    'LaunchVPS',
    'Rapid Systems',
    'Intelligence Network',
    'Trustwave',
    'Google',
    'Cloudflare',
    'Leaseweb',
    'Facebook',
    'Aspect',
    'Astute',
    'Nuance',
    'Creative Virtual',
    'IBM',
    'RASA',
    'CogniCor',
    'Inbenta',
    'Avaamo',
    'Nuance',
    'Apple'
]
